<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Eng_Ldr</name>
   <tag></tag>
   <elementGuidId>d2f550a9-34bc-419b-9f45-c03e6bd23c48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@data-test-id=&quot;2015051108211603597210-Label&quot;]//following-sibling::div</value>
   </webElementProperties>
</WebElementEntity>
