<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_PegaGadget0Ifr</name>
   <tag></tag>
   <elementGuidId>81b0bc91-8484-48d4-ab5f-7661debfa21a</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PegaGadget0Ifr&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/tcpqa/PRServlet/1x7owqsm--REl3ZnpfaW-lmDmY03UoO9*/!TABTHREAD0?pyActivity=%40baseclass.doUIAction&amp;action=display&amp;harnessName=COEDashboard&amp;className=Data-Portal&amp;contentID=11a003a8-8c90-4403-8bad-21d52c7b04fc&amp;dynamicContainerID=ea116240-74c5-4e95-b65b-4856fb4df9a1&amp;tabIndex=1&amp;portalThreadName=STANDARD&amp;portalName=COEUserPortal7&amp;pzHarnessID=HID89EC623739E52A981EB3882CA849585F</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PegaGadget0Ifr</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PegaGadget0Ifr</value>
   </webElementProperties>
</WebElementEntity>
