<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_CustomerSuccess</name>
   <tag></tag>
   <elementGuidId>4ecf594a-83ff-4396-adb6-f661cd8dc40d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//label[@for='PSDCustomerSuccessYellow'][count(. | //label[@ref_element = 'Object Repository/ESU_Obj/Frames/iframe_PegaGadget1Ifr']) = count(//label[@ref_element = 'Object Repository/ESU_Obj/Frames/iframe_PegaGadget1Ifr'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//label[@for='PSDCustomerSuccessYellow']</value>
   </webElementProperties>
</WebElementEntity>
