<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Prac_Ldr</name>
   <tag></tag>
   <elementGuidId>07ffa09c-c192-47aa-b40b-05237bf86bfc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@data-test-id=&quot;2015051108211603564320-Label&quot;]//following-sibling::div</value>
   </webElementProperties>
</WebElementEntity>
